### ISSUE TITLE
Demo page breaks in Chrome with Mixed Content (http/https) error

### ISSUE THREAD

**Issue by floledermann** [danmarshall/svg-path-outline#3]
The maker.js library seems to have relocated and the old URL seems to send a redirect through insecure http, triggering a "Mixed Content" warning in recent Chrome, refusing to run the script.

You should be able to fix this by changing the URL of the library to its new location at https://maker.js.org/target/js/browser.maker.js

**Comment by danmarshall** [comment]
Thanks for reporting this @floledermann ! Fixed now. :)
